import React, { useState, useMemo, useEffect } from 'react';
import type {
  Manifest,
  OptionPropDef,
  PrimitivePropDef,
  PropDef,
} from '@rplite/plugin/manifest';
import { Controls } from './Controls';
import { Preview } from './Preview';

/**
 * Props for the main Playground component.
 */
interface PlaygroundProps {
  /**
   * The component manifest generated by the Vite plugin.
   */
  manifest: Manifest;
}

// Internal styles for the playground layout.
// Using inline styles to keep the runtime self-contained and avoid CSS conflicts.
const playgroundStyles: React.CSSProperties = {
  display: 'flex',
  height: '100vh',
  width: '100vw',
  overflow: 'hidden',
  backgroundColor: '#f0f0f0',
};

const sidebarStyles: React.CSSProperties = {
  width: '250px',
  flexShrink: 0,
  backgroundColor: '#fff',
  borderRight: '1px solid #e0e0e0',
  padding: '16px',
  overflowY: 'auto',
  boxSizing: 'border-box',
};

const searchInputStyles: React.CSSProperties = {
  width: '100%',
  padding: '8px',
  fontSize: '14px',
  borderRadius: '4px',
  border: '1px solid #ccc',
  boxSizing: 'border-box',
  marginBottom: '12px',
};

const listStyles: React.CSSProperties = {
  listStyle: 'none',
  padding: 0,
  margin: 0,
};

const listItemStyles: React.CSSProperties = {
  padding: '8px 12px',
  cursor: 'pointer',
  borderRadius: '4px',
  marginBottom: '4px',
};

const controlsPanelStyles: React.CSSProperties = {
  width: '300px',
  flexShrink: 0,
  backgroundColor: '#fff',
  borderRight: '1px solid #e0e0e0',
  overflowY: 'auto',
  boxSizing: 'border-box',
};

const previewPanelStyles: React.CSSProperties = {
  flexGrow: 1,
  position: 'relative',
};

const SAMPLE_TAGS = ['Design', 'Analytics', 'Collaboration'];

function getInitialPropValue(propDef: PropDef): unknown {
  switch (propDef.type) {
    case 'string':
      return 'Sample text';
    case 'number':
      return 1;
    case 'boolean':
      return true;
    case 'union':
    case 'enum':
      return propDef.options[0] ?? '';
    case 'array':
      return getArrayInitialValues(propDef.element);
    default:
      return undefined;
  }
}

function getArrayInitialValues(
  element: PrimitivePropDef | OptionPropDef,
): unknown[] {
  switch (element.type) {
    case 'string':
      return [...SAMPLE_TAGS];
    case 'number':
      return [25, 75];
    case 'boolean':
      return [true];
    case 'union':
    case 'enum':
      return element.options.length > 0 ? [element.options[0]] : [];
    default:
      return [];
  }
}

/**
 * The main UI of the React Playground.
 * It consists of a component list, a controls panel for props, and a preview area.
 * @param {PlaygroundProps} props The component props.
 */
export function Playground({ manifest }: PlaygroundProps) {
  // The ID of the selected component, in the format "path:name".
  const [selectedComponentId, setSelectedComponentId] = useState<string | null>(
    null,
  );
  // Search query for filtering component list.
  const [query, setQuery] = useState('');
  // The current values of the props for the selected component.
  const [propValues, setPropValues] = useState<Record<string, any>>({});

  // Memoized sorted list of components for display in the sidebar.
  const sortedComponents = useMemo(() => {
    return [...manifest.components].sort((a, b) => {
      // Create a sortable key, prioritizing default exports.
      const aName = a.isDefaultExport ? a.path : `${a.path} / ${a.name}`;
      const bName = b.isDefaultExport ? b.path : `${b.path} / ${b.name}`;
      return aName.localeCompare(bName);
    });
  }, [manifest.components]);

  // Filtered list of components based on the search query.
  const filteredComponents = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return sortedComponents;
    return sortedComponents.filter(c => {
      const filename = c.path.split('/').pop() ?? c.path;
      const displayName = c.isDefaultExport
        ? filename.replace(/\.tsx?$/, '')
        : `${filename.replace(/\.tsx?$/, '')} / ${c.name}`;
      return (
        displayName.toLowerCase().includes(q) ||
        c.path.toLowerCase().includes(q) ||
        c.name.toLowerCase().includes(q)
      );
    });
  }, [sortedComponents, query]);

  // Effect to select the first component by default.
  useEffect(() => {
    if (!selectedComponentId && sortedComponents.length > 0) {
      const firstComponent = sortedComponents[0];
      setSelectedComponentId(`${firstComponent.path}:${firstComponent.name}`);
    }
  }, [sortedComponents, selectedComponentId]);

  // Memoized definition of the currently selected component.
  const selectedComponent = useMemo(() => {
    if (!selectedComponentId) return null;
    const [path, name] = selectedComponentId.split(':');
    return (
      manifest.components.find(c => c.path === path && c.name === name) ?? null
    );
  }, [selectedComponentId, manifest.components]);

  // Effect to initialize prop values when the selected component changes.
  useEffect(() => {
    if (selectedComponent) {
      const initialProps: Record<string, any> = {};
      for (const [propName, propDef] of Object.entries(
        selectedComponent.props,
      )) {
        const value = getInitialPropValue(propDef);
        if (value !== undefined) {
          initialProps[propName] = value;
        }
      }
      setPropValues(initialProps);
    } else {
      setPropValues({});
    }
  }, [selectedComponent]);

  /**
   * Handles changes to a prop's value from the Controls panel.
   */
  const handleValueChange = (propName: string, value: any) => {
    setPropValues(prev => ({ ...prev, [propName]: value }));
  };

  return (
    <div style={playgroundStyles}>
      {/* Sidebar with the list of discovered components */}
      <aside style={sidebarStyles}>
        <h2 style={{ fontSize: '18px', marginTop: 0 }}>Components</h2>
        <input
          type="search"
          placeholder="Search components..."
          value={query}
          onChange={e => setQuery(e.target.value)}
          aria-label="Search components"
          style={searchInputStyles}
        />
        <ul style={listStyles}>
          {filteredComponents.map(c => {
            const id = `${c.path}:${c.name}`;
            // Generate a user-friendly display name.
            const displayName = c.isDefaultExport
              ? c.path.split('/').pop()?.replace(/\.tsx?$/, '')
              : `${c.path.split('/').pop()?.replace(/\.tsx?$/, '')} / ${c.name}`;

            return (
              <li
                key={id}
                onClick={() => setSelectedComponentId(id)}
                style={{
                  ...listItemStyles,
                  backgroundColor:
                    selectedComponentId === id ? '#e0eafc' : 'transparent',
                  fontWeight: selectedComponentId === id ? 600 : 'normal',
                }}
              >
                {displayName}
              </li>
            );
          })}
        </ul>
      </aside>

      {/* Main content area with controls and preview */}
      {selectedComponent ? (
        <>
          <aside style={controlsPanelStyles}>
            <Controls
              component={selectedComponent}
              values={propValues}
              onValueChange={handleValueChange}
            />
          </aside>
          <main style={previewPanelStyles}>
            <Preview component={selectedComponent} props={propValues} />
          </main>
        </>
      ) : (
        <main
          style={{ ...previewPanelStyles, display: 'grid', placeContent: 'center' }}
        >
          <p>Select a component to preview</p>
        </main>
      )}
    </div>
  );
}
