import React, { useState, useMemo, useEffect } from 'react';
import type { Manifest } from '@rplite/plugin/manifest';
import { Controls } from './Controls';
import { Preview } from './Preview';

/**
 * Props for the main Playground component.
 */
interface PlaygroundProps {
  /**
   * The component manifest generated by the Vite plugin.
   */
  manifest: Manifest;
}

// Internal styles for the playground layout.
// Using inline styles to keep the runtime self-contained and avoid CSS conflicts.
const playgroundStyles: React.CSSProperties = {
  display: 'flex',
  height: '100vh',
  width: '100vw',
  overflow: 'hidden',
  backgroundColor: '#f0f0f0',
};

const sidebarStyles: React.CSSProperties = {
  width: '250px',
  flexShrink: 0,
  backgroundColor: '#fff',
  borderRight: '1px solid #e0e0e0',
  padding: '16px',
  overflowY: 'auto',
  boxSizing: 'border-box',
};

const listStyles: React.CSSProperties = {
  listStyle: 'none',
  padding: 0,
  margin: 0,
};

const listItemStyles: React.CSSProperties = {
  padding: '8px 12px',
  cursor: 'pointer',
  borderRadius: '4px',
  marginBottom: '4px',
};

const controlsPanelStyles: React.CSSProperties = {
  width: '300px',
  flexShrink: 0,
  backgroundColor: '#fff',
  borderRight: '1px solid #e0e0e0',
  overflowY: 'auto',
  boxSizing: 'border-box',
};

const previewPanelStyles: React.CSSProperties = {
  flexGrow: 1,
  position: 'relative',
};

/**
 * The main UI of the React Playground.
 * It consists of a component list, a controls panel for props, and a preview area.
 * @param {PlaygroundProps} props The component props.
 */
export function Playground({ manifest }: PlaygroundProps) {
  // The ID of the selected component, in the format "path:name".
  const [selectedComponentId, setSelectedComponentId] = useState<string | null>(
    null,
  );
  // The current values of the props for the selected component.
  const [propValues, setPropValues] = useState<Record<string, any>>({});

  // Memoized sorted list of components for display in the sidebar.
  const sortedComponents = useMemo(() => {
    return [...manifest.components].sort((a, b) => {
      // Create a sortable key, prioritizing default exports.
      const aName = a.isDefaultExport ? a.path : `${a.path} / ${a.name}`;
      const bName = b.isDefaultExport ? b.path : `${b.path} / ${b.name}`;
      return aName.localeCompare(bName);
    });
  }, [manifest.components]);

  // Effect to select the first component by default.
  useEffect(() => {
    if (!selectedComponentId && sortedComponents.length > 0) {
      const firstComponent = sortedComponents[0];
      setSelectedComponentId(`${firstComponent.path}:${firstComponent.name}`);
    }
  }, [sortedComponents, selectedComponentId]);

  // Memoized definition of the currently selected component.
  const selectedComponent = useMemo(() => {
    if (!selectedComponentId) return null;
    const [path, name] = selectedComponentId.split(':');
    return (
      manifest.components.find(c => c.path === path && c.name === name) ?? null
    );
  }, [selectedComponentId, manifest.components]);

  // Effect to initialize prop values when the selected component changes.
  useEffect(() => {
    if (selectedComponent) {
      const initialProps: Record<string, any> = {};
      // Set default values for certain prop types.
      for (const [propName, propDef] of Object.entries(
        selectedComponent.props,
      )) {
        if (propDef.type === 'boolean') {
          initialProps[propName] = false;
        } else if (
          (propDef.type === 'union' || propDef.type === 'enum') &&
          propDef.options.length > 0
        ) {
          initialProps[propName] = propDef.options[0];
        } else if (propDef.type === 'array') {
          initialProps[propName] = [];
        }
      }
      setPropValues(initialProps);
    } else {
      setPropValues({});
    }
  }, [selectedComponent]);

  /**
   * Handles changes to a prop's value from the Controls panel.
   */
  const handleValueChange = (propName: string, value: any) => {
    setPropValues(prev => ({ ...prev, [propName]: value }));
  };

  return (
    <div style={playgroundStyles}>
      {/* Sidebar with the list of discovered components */}
      <aside style={sidebarStyles}>
        <h2 style={{ fontSize: '18px', marginTop: 0 }}>Components</h2>
        <ul style={listStyles}>
          {sortedComponents.map(c => {
            const id = `${c.path}:${c.name}`;
            // Generate a user-friendly display name.
            const displayName = c.isDefaultExport
              ? c.path.split('/').pop()?.replace(/\.tsx?$/, '')
              : `${c.path.split('/').pop()?.replace(/\.tsx?$/, '')} / ${c.name}`;

            return (
              <li
                key={id}
                onClick={() => setSelectedComponentId(id)}
                style={{
                  ...listItemStyles,
                  backgroundColor:
                    selectedComponentId === id ? '#e0eafc' : 'transparent',
                  fontWeight: selectedComponentId === id ? 600 : 'normal',
                }}
              >
                {displayName}
              </li>
            );
          })}
        </ul>
      </aside>

      {/* Main content area with controls and preview */}
      {selectedComponent ? (
        <>
          <aside style={controlsPanelStyles}>
            <Controls
              component={selectedComponent}
              values={propValues}
              onValueChange={handleValueChange}
            />
          </aside>
          <main style={previewPanelStyles}>
            <Preview component={selectedComponent} props={propValues} />
          </main>
        </>
      ) : (
        <main
          style={{ ...previewPanelStyles, display: 'grid', placeContent: 'center' }}
        >
          <p>Select a component to preview</p>
        </main>
      )}
    </div>
  );
}
